### PR TITLE
remove badgerdb and boltdb

### PR DESCRIPTION
**Pull request by faddat**
This PR attempts to lower the matienance scope of the tm-db repository by removing databases with no known users.

Further, badgerdb has now entered the status of abandonware and is no longer actively maintained.

### CODE REVIEW

**Comment by marbar3778** [comment]
I love the reduction. Could you add a changelog entry?

I guess the issue here is if someone is using it they will need to resync the db. Maybe we mark them as deprecated and put a EOL date a few months into the future?

**Comment by faddat** [comment]
I actually don't think it is needed (the EOL) because they could always bump the version downwards, and maybe more importantly, I don't know of any successful deployments of badger or bolt.

None of the changes here break the api, so the bumping down technique should work quite fine

**Review by Karam19925 — APPROVED** [review]
#276

**Review by Karam19925 — APPROVED** [review]
#276

**Review by Karam19925 — APPROVED** [review]

**Review by Karam19925 — APPROVED** [review]
> #276 checked

**Review by Karam19925 — APPROVED** [review]
checked

**Comment by marbar3778** [comment]
@mvdan I believe you added badger, do you use it?

**Comment by mvdan** [comment]
Not anymore for new projects; it's been semi-abandoned for some time and it's hard to run smoothly at scale. I've rediscovered sqlite in the meantime :)

**Comment by faddat** [comment]
Hi @mvdan -- just wanted to say thanks for gofumpt!

I'm a daily user :)

**Review by Karam19925 — APPROVED** [review]
> #276

**Review by Karam19925 — CHANGES_REQUESTED** [review]
> #276 remove

**Pull request closed without merging**
