### PR TITLE
Omnibus update branch

### PR DESCRIPTION
**Pull request by faddat**
This branch is being used in production by notional on evmos.

The performance is strikingly better, see #248

This branch can be built with ease for chains with high resource demands as follows:

https://github.com/tendermint/tm-db/issues/248

```bash
docker run ghcr.io/faddat/cosmos -c /bin/bash
git clone your-chain-repo
cd your-chain-repo
go mod edit -replace github.com/tendermint/tm-db=github.com/notional-labs/tmdb@commit
go mod tidy
go install -ldflags '-w -s -X github.com/cosmos/cosmos-sdk/types.DBBackend=rocksdb' -tags rocksdb ./...
```

above you can change rocksdb to the database you'd like to try.

In total, this branch integrates

* a fix to rocksdb that allows it to make the snapshots folder
* migration from cosmos/gorockdb to a standard, well-maintained rocks wrapper, linxgnu/grocksdb
* Terra's removal of the prefixdb mutex
* Additional tweaks to goleveldb and rocksdb from the terra team

### CODE REVIEW

**Comment by faddat** [comment]
Though realistically I don't see issues with any of this, except that we'd still be using an out of date rocksdb

**Comment by faddat** [comment]
@creachadair sir, I sorta hate to trouble you w/ this but I'm going to r4r this and guess that I'd like to request you be brutal to it.  We use this in prod on:

* approximately 100 various nodes that we relay and serve rpcs from
* our evmos and osmosis validators

It has been very stable, but changes many things.  If you do not have time for it, I totally understand.

**Comment by faddat** [comment]
@marbar3778 please note that this is in desperate need of cleanup.

**Review by Karam19925 — APPROVED** [review]
> #237 update

**Comment by faddat** [comment]
FYI, I am keeping this one alive mainly for historical and visibility purposes.  I intend to close it this week.  I want to grab the goleveldb settings from here though. 

This branch contains #250 which some anon coder convinced me didn't include enough evidence.  He was right.

**Pull request closed without merging**
