### PR TITLE
fix cleveldb Stats()

### PR DESCRIPTION
**Pull request by luohaha**
Remove unmatch property keys and add useful property key. 
https://github.com/google/leveldb/blob/main/db/db_impl.cc#L1387

### CODE REVIEW

**Comment by faddat** [comment]
Ahhhhh got it.  Does this fix the issue I mentioned in #275 ?

Thank you

**Comment by luohaha** [comment]
> Ahhhhh got it. Does this fix the issue I mentioned in #275 ?
> 
> Thank you

It doesn't fix your issue. The change I make is just for fixing stats() in cleveldb.

**Comment by faddat** [comment]
oh, I wonder (lots) what's going on there!

Thanks for the patch

**Comment by faddat** [comment]
Fixed it.  It was the certificates, I think they'd expired.

**Comment by luohaha** [comment]
> 

Yeah, I am using cleveldb, and when I want to print some internal statistics in cleveldb, it can't work.

**Review by marbar3778 — APPROVED** [review]

**Comment by marbar3778** [comment]
seems tests area failing, @luohaha could take a look?

**Comment by faddat** [comment]
Tests are failing because #280 is not merged into this branch.  In my branches, test pass, only because I merged it in.

eg: master is broken.

**Comment by luohaha** [comment]
> Tests are failing because #280 is not merged into this branch. In my branches, test pass, only because I merged it in.
> 
> eg: master is broken.

Thanks, I misunderstand what you say before.

**Pull request merged**
